import { Eta } from "eta";

export function renderConstantsFile(eta: Eta, data: ConstantsTemplate): string {
    return eta.renderString(constantsTemplate, data);
}

export type ConstantsTemplate = {
  className: string,
  typeName: string;
  variables: Map<string, string>,
}

const constantsTemplate = `
import 'package:flutter/material.dart';

/* This file was generated by Supernova, don't change by hand */
@immutable
class <%=it.className%> {
  <% for (var name in it.variables) {%>
  static const <%=it.typeName%> <%=name%> = <%=it.variables[name]%>;
  <% } %>
}
`

