import { Eta } from "eta";

export function renderPrimitiveColors(eta: Eta, data: PrimitiveColorsTemplateData): string {
    return eta.renderString(primitiveColorsTemplate, data);
}

export type PrimitiveColorsTemplateData = {
  className: string,
  swatches: Map<string, Map<string, string>>,
  colors: Map<string, string>
}

const primitiveColorsTemplate = `
import 'package:flutter/material.dart';
import 'package:sev_design_tokens/src/colors/offenburg_color_swatch.dart';

/* This file was generated by Supernova, don't change by hand */
class <%=it.className%> {
  <% for(var swatch in it.swatches) {%>
  static const OffenburgColorSwatch <%=swatch%> = OffenburgColorSwatch(
    0xFF20A381,
    {
      <% for(var shade in it.swatches[swatch]) {%>
      OffenburgColorShade.shade<%=shade%>: <%=it.swatches[swatch][shade]%>,
      <% } %>
    },
  );<% } %>

  <% for (var color in it.colors) {%>
  static const Color <%=color%> = <%=it.colors[color]%>;
  <% } %>
}
`


