import { Eta } from "eta";

export function renderShadows(eta: Eta, data: ShadowTemplate): string {
  return eta.renderString(shadowsTemplate, data);
}

export type ShadowData = {
  color: string,
  blurStyle: string,
  offsetX: string,
  offsetY: string,
  blurRadius: string,
  spreadRadius: string,
}

export type ShadowTemplate = {
  className: string,
  variables: Map<string, ShadowData>,
}

const shadowsTemplate = `
import 'package:flutter/material.dart';

/* This file was generated by Supernova, don't change by hand */
@immutable
class <%=it.className%> {

  <% for (var name in it.variables) {%>
  <% var shadow = it.variables[name] %>
  static const BoxShadow <%=name%> = BoxShadow(
    color: <%=shadow.color%>,
    blurStyle: <%=shadow.blurStyle%>,
    offset: Offset(<%=shadow.offsetX%>, <%=shadow.offsetY%>),
    blurRadius: <%=shadow.blurRadius%>,
    spreadRadius: <%=shadow.spreadRadius%>,
  );
  <% } %>
}
`